<?php
/**
 * Blueprint export builder.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WPBE_Exporter {
	const SCHEMA_URL = 'https://playground.wordpress.net/blueprint-schema.json';

	/**
	 * Build a Blueprint array from the current site state.
	 *
	 * @param array $settings Export settings.
	 * @return array
	 */
	public function build_blueprint( array $settings ) {
		$settings = wp_parse_args(
			$settings,
			array(
				'include_plugins'      => true,
				'include_theme'        => true,
				'include_site_options' => true,
				'include_login'        => true,
				'php_version'          => '8.3',
				'wp_version'           => 'latest',
				'landing_page'         => '/wp-admin/',
			)
		);

		$blueprint = array(
			'$schema'           => self::SCHEMA_URL,
			'meta'              => array(
				'title'       => $this->get_site_title(),
				'description' => 'Generated by WP Blueprint Exporter.',
				'author'      => $this->get_author_slug(),
				'categories'  => array( 'generated' ),
			),
			'landingPage'       => $this->sanitize_landing_page( $settings['landing_page'] ),
			'preferredVersions' => array(
				'php' => sanitize_text_field( $settings['php_version'] ),
				'wp'  => sanitize_text_field( $settings['wp_version'] ),
			),
			'steps'             => array(),
		);

		if ( ! empty( $settings['include_site_options'] ) ) {
			$blueprint['siteOptions'] = $this->get_site_options();
		}

		if ( ! empty( $settings['include_plugins'] ) ) {
			$plugin_slugs = $this->get_active_plugin_slugs();

			if ( ! empty( $plugin_slugs ) ) {
				$blueprint['features'] = array( 'networking' => true );
				$blueprint['plugins']  = $plugin_slugs;
			}
		}

		if ( ! empty( $settings['include_login'] ) ) {
			$blueprint['steps'][] = array(
				'step'     => 'login',
				'username' => 'admin',
				'password' => 'password',
			);
		}

		if ( ! empty( $settings['include_theme'] ) ) {
			$theme_step = $this->get_active_theme_step();

			if ( null !== $theme_step ) {
				$blueprint['features'] = array( 'networking' => true );
				$blueprint['steps'][]  = $theme_step;
			}
		}

		return $this->remove_empty_values( $blueprint );
	}

	/**
	 * Return a pretty JSON representation of a Blueprint.
	 *
	 * @param array $blueprint Blueprint data.
	 * @return string
	 */
	public function to_json( array $blueprint ) {
		return wp_json_encode( $blueprint, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) . "\n";
	}

	/**
	 * Get active plugin slugs for wordpress.org-style plugins.
	 *
	 * @return array
	 */
	public function get_active_plugin_slugs() {
		$active_plugins = (array) get_option( 'active_plugins', array() );
		$slugs          = array();

		foreach ( $active_plugins as $plugin_file ) {
			if ( WPBE_PLUGIN_FILE === WP_PLUGIN_DIR . '/' . $plugin_file ) {
				continue;
			}

			$slug = $this->plugin_file_to_slug( $plugin_file );

			if ( '' !== $slug ) {
				$slugs[] = $slug;
			}
		}

		$slugs = array_values( array_unique( $slugs ) );
		sort( $slugs );

		return $slugs;
	}

	/**
	 * Convert a plugin basename into a likely wordpress.org slug.
	 *
	 * @param string $plugin_file Plugin basename.
	 * @return string
	 */
	private function plugin_file_to_slug( $plugin_file ) {
		$plugin_file = sanitize_text_field( $plugin_file );

		if ( false !== strpos( $plugin_file, '/' ) ) {
			return sanitize_title( dirname( $plugin_file ) );
		}

		return sanitize_title( basename( $plugin_file, '.php' ) );
	}

	/**
	 * Get installTheme step for the active theme.
	 *
	 * @return array|null
	 */
	private function get_active_theme_step() {
		$theme = wp_get_theme();
		$slug  = sanitize_title( $theme->get_stylesheet() );

		if ( '' === $slug ) {
			return null;
		}

		return array(
			'step'      => 'installTheme',
			'themeData' => array(
				'resource' => 'wordpress.org/themes',
				'slug'     => $slug,
			),
			'options'   => array(
				'activate' => true,
			),
		);
	}

	/**
	 * Get safe site options for Blueprint export.
	 *
	 * @return array
	 */
	private function get_site_options() {
		$options = array(
			'blogname'        => get_option( 'blogname' ),
			'blogdescription' => get_option( 'blogdescription' ),
			'date_format'     => get_option( 'date_format' ),
			'time_format'     => get_option( 'time_format' ),
			'start_of_week'   => (string) get_option( 'start_of_week' ),
			'timezone_string' => get_option( 'timezone_string' ),
			'permalink_structure' => get_option( 'permalink_structure' ),
		);

		return array_filter(
			$options,
			static function ( $value ) {
				return null !== $value && '' !== $value;
			}
		);
	}

	/**
	 * Get a title for Blueprint metadata.
	 *
	 * @return string
	 */
	private function get_site_title() {
		$title = get_option( 'blogname' );

		if ( empty( $title ) ) {
			return 'Generated WordPress Blueprint';
		}

		return $title . ' Blueprint';
	}

	/**
	 * Get a lightweight author slug.
	 *
	 * @return string
	 */
	private function get_author_slug() {
		$user = wp_get_current_user();

		if ( $user instanceof WP_User && $user->exists() ) {
			return sanitize_title( $user->user_login );
		}

		return 'wp-blueprint-exporter';
	}

	/**
	 * Keep the landing page as an absolute path.
	 *
	 * @param string $landing_page Landing page.
	 * @return string
	 */
	private function sanitize_landing_page( $landing_page ) {
		$landing_page = trim( sanitize_text_field( $landing_page ) );

		if ( '' === $landing_page || '/' !== $landing_page[0] ) {
			return '/wp-admin/';
		}

		return $landing_page;
	}

	/**
	 * Remove empty arrays from top-level output.
	 *
	 * @param array $value Value to clean.
	 * @return array
	 */
	private function remove_empty_values( array $value ) {
		foreach ( $value as $key => $item ) {
			if ( is_array( $item ) ) {
				$item = $this->remove_empty_values( $item );
			}

			if ( array() === $item || null === $item || '' === $item ) {
				unset( $value[ $key ] );
				continue;
			}

			$value[ $key ] = $item;
		}

		return $value;
	}
}
